//---------------------------------------------------------------------------
//	Greenplum Database
//	Copyright (C) 2011 EMC Corp.
//
//	@filename:
//		CPhysicalJoin.h
//
//	@doc:
//		Physical join base class
//---------------------------------------------------------------------------
#ifndef GPOPT_CPhysicalJoin_H
#define GPOPT_CPhysicalJoin_H

#include "gpos/base.h"

#include "gpopt/base/CDistributionSpec.h"
#include "gpopt/operators/CPhysical.h"
#include "gpopt/xforms/CXform.h"

namespace gpopt
{
// fwd declarations
class CDistributionSpecSingleton;

//---------------------------------------------------------------------------
//	@class:
//		CPhysicalJoin
//
//	@doc:
//		Inner nested-loops join operator
//
//---------------------------------------------------------------------------
class CPhysicalJoin : public CPhysical
{
private:
	// private copy ctor
	CPhysicalJoin(const CPhysicalJoin &);

	// check whether the child being processed is the child that has the part consumer
	static GP_BOOL FProcessingChildWithPartConsumer(GP_BOOL fOuterPartConsumerTest,
												 GP_ULONG ulChildIndexToTestFirst,
												 GP_ULONG ulChildIndexToTestSecond,
												 GP_ULONG child_index);

	// xform that join order originated from
	CXform::EXformId m_origin_xform;

protected:
	// Partition propagation request generated by a join
	class CPartPropReq : public CRefCount
	{
	private:
		// required part propagation
		CPartitionPropagationSpec *m_pppsRequired;

		// child index to push requirements to
		GP_ULONG m_ulChildIndex;

		// id of outer child
		GP_ULONG m_ulOuterChild;

		// id of inner child
		GP_ULONG m_ulInnerChild;

		// id of scalar child
		GP_ULONG m_ulScalarChild;

		// private copy ctor
		CPartPropReq(const CPartPropReq &);

	public:
		// ctor
		CPartPropReq(CPartitionPropagationSpec *pppsRequired, GP_ULONG child_index,
					 GP_ULONG ulOuterChild, GP_ULONG ulInnerChild,
					 GP_ULONG ulScalarChild)
			: m_pppsRequired(pppsRequired),
			  m_ulChildIndex(child_index),
			  m_ulOuterChild(ulOuterChild),
			  m_ulInnerChild(ulInnerChild),
			  m_ulScalarChild(ulScalarChild)
		{
			GPOS_ASSERT(NULL != pppsRequired);
		}

		// dtor
		virtual ~CPartPropReq()
		{
			m_pppsRequired->Release();
		}

		// partition propgataion spec
		CPartitionPropagationSpec *
		Ppps() const
		{
			return m_pppsRequired;
		}

		// child index to push requirements to
		GP_ULONG
		UlChildIndex() const
		{
			return m_ulChildIndex;
		}

		// outer child id
		GP_ULONG
		UlOuterChild() const
		{
			return m_ulOuterChild;
		}

		// inner child id
		GP_ULONG
		UlInnerChild() const
		{
			return m_ulInnerChild;
		}

		// scalar child id
		GP_ULONG
		UlScalarChild() const
		{
			return m_ulScalarChild;
		}

		// hash function
		static GP_ULONG HashValue(const CPartPropReq *pppr);

		// equality function
		static GP_BOOL Equals(const CPartPropReq *ppprFst,
						   const CPartPropReq *ppprSnd);

	};	// class CPartPropReq

	// map partition propagation request to partition propagation spec
	typedef CHashMap<CPartPropReq, CPartitionPropagationSpec,
					 CPartPropReq::HashValue, CPartPropReq::Equals,
					 CleanupRelease<CPartPropReq>,
					 CleanupRelease<CPartitionPropagationSpec> >
		PartPropReqToPartPropSpecMap;

	// partition propagation request map
	PartPropReqToPartPropSpecMap *m_phmpp;

	// ctor
	explicit CPhysicalJoin(CMemoryPool *mp,
						   CXform::EXformId origin_xform = CXform::ExfSentinel);

	// dtor
	virtual ~CPhysicalJoin();

	// helper to check if given child index correspond to first child to be optimized
	GP_BOOL FFirstChildToOptimize(GP_ULONG child_index) const;

	// helper to compute required distribution of correlated join's children
	CEnfdDistribution *PedCorrelatedJoin(
		CMemoryPool *mp, CExpressionHandle &exprhdl, CReqdPropPlan *prppInput,
		GP_ULONG child_index, CDrvdPropArray *pdrgpdpCtxt, GP_ULONG ulOptReq);

	// helper to compute required rewindability of correlated join's children
	CRewindabilitySpec *PrsRequiredCorrelatedJoin(
		CMemoryPool *mp, CExpressionHandle &exprhdl,
		CRewindabilitySpec *prsRequired, GP_ULONG child_index,
		CDrvdPropArray *pdrgpdpCtxt, GP_ULONG ulOptReq) const;

	// create partition propagation request
	CPartPropReq *PpprCreate(CMemoryPool *mp, CExpressionHandle &exprhdl,
							 CPartitionPropagationSpec *pppsRequired,
							 GP_ULONG child_index);

	// compute required partition propagation of the n-th child
	CPartitionPropagationSpec *PppsRequiredCompute(
		CMemoryPool *mp, CExpressionHandle &exprhdl,
		CPartitionPropagationSpec *pppsRequired, GP_ULONG child_index,
		GP_BOOL fNLJoin);

	// helper function for computing the required partition propagation
	// spec for the children of a join
	CPartitionPropagationSpec *PppsRequiredJoinChild(
		CMemoryPool *mp, CExpressionHandle &exprhdl,
		CPartitionPropagationSpec *pppsRequired, GP_ULONG child_index,
		CDrvdPropArray *pdrgpdpCtxt, GP_BOOL fNLJoin);

	// helper for propagating required sort order to outer child
	static COrderSpec *PosPropagateToOuter(CMemoryPool *mp,
										   CExpressionHandle &exprhdl,
										   COrderSpec *posRequired);

	// helper for checking if required sort columns come from outer child
	static GP_BOOL FSortColsInOuterChild(CMemoryPool *mp,
									  CExpressionHandle &exprhdl,
									  COrderSpec *pos);

	// helper for checking if the outer input of a binary join operator
	// includes the required columns
	static GP_BOOL FOuterProvidesReqdCols(CExpressionHandle &exprhdl,
									   CColRefSet *pcrsRequired);


	// helper to add filter on part key
	static void AddFilterOnPartKey(
		CMemoryPool *mp, GP_BOOL fNLJoin, CExpression *pexprScalar,
		CPartIndexMap *ppimSource, CPartFilterMap *ppfmSource,
		GP_ULONG child_index, GP_ULONG part_idx_id, GP_BOOL fOuterPartConsumer,
		CPartIndexMap *ppimResult, CPartFilterMap *ppfmResult,
		CColRefSet *pcrsAllowedRefs);

	// helper to find join predicates on part keys. Returns NULL if not found
	static CExpression *PexprJoinPredOnPartKeys(CMemoryPool *mp,
												CExpression *pexprScalar,
												CPartIndexMap *ppimSource,
												GP_ULONG part_idx_id,
												CColRefSet *pcrsAllowedRefs);

	// Do each of the given predicate children use columns from a different
	// join child?
	static GP_BOOL FPredKeysSeparated(CExpression *pexprOuter,
								   CExpression *pexprInner,
								   CExpression *pexprPredOuter,
								   CExpression *pexprPredInner);

	static CEnfdDistribution *PedInnerHashedFromOuterHashed(
		CMemoryPool *mp, CExpressionHandle &exprhdl,
		CEnfdDistribution::EDistributionMatching dmatch,
		CDrvdProp *outerDrvdProp);

public:
	// match function
	GP_BOOL Matches(COperator *pop) const;

	// sensitivity to order of inputs
	GP_BOOL
	FInputOrderSensitive() const
	{
		return true;
	}

	//-------------------------------------------------------------------------------------
	// Required Plan Properties
	//-------------------------------------------------------------------------------------

	// compute required output columns of the n-th child
	virtual CColRefSet *PcrsRequired(
		CMemoryPool *mp, CExpressionHandle &exprhdl, CColRefSet *pcrsRequired,
		GP_ULONG child_index, CDrvdPropArray *pdrgpdpCtxt, GP_ULONG ulOptReq);

	// compute required ctes of the n-th child
	virtual CCTEReq *PcteRequired(CMemoryPool *mp, CExpressionHandle &exprhdl,
								  CCTEReq *pcter, GP_ULONG child_index,
								  CDrvdPropArray *pdrgpdpCtxt,
								  GP_ULONG ulOptReq) const;

	// compute required distribution of the n-th child
	virtual CDistributionSpec *PdsRequired(CMemoryPool *mp,
										   CExpressionHandle &exprhdl,
										   CDistributionSpec *pdsRequired,
										   GP_ULONG child_index,
										   CDrvdPropArray *pdrgpdpCtxt,
										   GP_ULONG ulOptReq) const;

	virtual CEnfdDistribution *Ped(CMemoryPool *mp, CExpressionHandle &exprhdl,
								   CReqdPropPlan *prppInput, GP_ULONG child_index,
								   CDrvdPropArray *pdrgpdpCtxt,
								   GP_ULONG ulDistrReq);

	// compute required partition propagation of the n-th child
	virtual CPartitionPropagationSpec *PppsRequired(
		CMemoryPool *mp, CExpressionHandle &exprhdl,
		CPartitionPropagationSpec *pppsRequired, GP_ULONG child_index,
		CDrvdPropArray *pdrgpdpCtxt, GP_ULONG ulOptReq);

	// check if required columns are included in output columns
	virtual GP_BOOL FProvidesReqdCols(CExpressionHandle &exprhdl,
								   CColRefSet *pcrsRequired,
								   GP_ULONG ulOptReq) const;

	// distribution matching type
	virtual CEnfdDistribution::EDistributionMatching Edm(
		CReqdPropPlan *prppInput, GP_ULONG child_index,
		CDrvdPropArray *pdrgpdpCtxt, GP_ULONG ulOptReq);

	//-------------------------------------------------------------------------------------
	// Derived Plan Properties
	//-------------------------------------------------------------------------------------

	// derive sort order from outer child
	virtual COrderSpec *
	PosDerive(CMemoryPool *,  // mp
			  CExpressionHandle &exprhdl) const
	{
		return PosDerivePassThruOuter(exprhdl);
	}

	// derive distribution
	virtual CDistributionSpec *PdsDerive(CMemoryPool *mp,
										 CExpressionHandle &exprhdl) const;

	// derive rewindability
	virtual CRewindabilitySpec *PrsDerive(CMemoryPool *mp,
										  CExpressionHandle &exprhdl) const;

	// derive partition index map
	virtual CPartIndexMap *
	PpimDerive(CMemoryPool *mp, CExpressionHandle &exprhdl,
			   CDrvdPropCtxt *	//pdpctxt
	) const
	{
		return PpimDeriveCombineRelational(mp, exprhdl);
	}

	// derive partition filter map
	virtual CPartFilterMap *
	PpfmDerive(CMemoryPool *mp, CExpressionHandle &exprhdl) const
	{
		// combine part filter maps from relational children
		return PpfmDeriveCombineRelational(mp, exprhdl);
	}


	//-------------------------------------------------------------------------------------
	// Enforced Properties
	//-------------------------------------------------------------------------------------

	// return rewindability property enforcing type for this operator
	virtual CEnfdProp::EPropEnforcingType EpetRewindability(
		CExpressionHandle &exprhdl, const CEnfdRewindability *per) const;

	// return true if operator passes through stats obtained from children,
	// this is used when computing stats during costing
	virtual GP_BOOL
	FPassThruStats() const
	{
		return false;
	}

	CXform::EXformId
	OriginXform()
	{
		return m_origin_xform;
	}
	//-------------------------------------------------------------------------------------
	//-------------------------------------------------------------------------------------
	//-------------------------------------------------------------------------------------

	// is given predicate hash-join compatible
	static GP_BOOL FHashJoinCompatible(CExpression *pexprPred,
									CExpression *pexprOuter,
									CExpression *pexprInner);

	// is given predicate merge-join compatible
	static GP_BOOL FMergeJoinCompatible(CExpression *pexprPred,
									 CExpression *pexprOuter,
									 CExpression *pexprInner);

	// return number of distribution requests for correlated join
	static GP_ULONG UlDistrRequestsForCorrelatedJoin();

	static void AlignJoinKeyOuterInner(CExpression *pexprConjunct,
									   CExpression *pexprOuter,
									   CExpression *pexprInner,
									   CExpression **ppexprKeyOuter,
									   CExpression **ppexprKeyInner,
									   IMDId **mdid_scop);

	static CRewindabilitySpec *PrsRequiredForNLJoinOuterChild(
		CMemoryPool *pmp, CExpressionHandle &exprhdl,
		CRewindabilitySpec *prsRequired);

};	// class CPhysicalJoin

}  // namespace gpopt

#endif	// !GPOPT_CPhysicalJoin_H

// EOF
