set(CMAKE_CXX_FLAGS " -Wno-template-body -Wno-undefined-var-template")

add_library_unity(
        duckdb_gporca
        OBJECT
	gpopt/base/CAutoOptCtxt.cpp
	gpopt/base/CCastUtils.cpp
	gpopt/base/CColConstraintsArrayMapper.cpp
	gpopt/base/CColConstraintsHashMapper.cpp
	gpopt/base/CColRef.cpp
	gpopt/base/CColRefComputed.cpp
	gpopt/base/CColRefSet.cpp
	gpopt/base/CColRefSetIter.cpp
	gpopt/base/CColRefTable.cpp
	gpopt/base/CColumnFactory.cpp
	gpopt/base/CConstraint.cpp
	gpopt/base/CConstraintConjunction.cpp
	gpopt/base/CConstraintDisjunction.cpp
	gpopt/base/CConstraintInterval.cpp
	gpopt/base/CConstraintNegation.cpp
	gpopt/base/CCostContext.cpp
	gpopt/base/CCTEInfo.cpp
	gpopt/base/CCTEMap.cpp
	gpopt/base/CCTEReq.cpp
	gpopt/base/CDefaultComparator.cpp
	gpopt/base/CDistributionSpecHashed.cpp
	gpopt/base/CDistributionSpecHashedNoOp.cpp
	gpopt/base/CDistributionSpecNonSingleton.cpp
	gpopt/base/CDistributionSpecRandom.cpp
	gpopt/base/CDistributionSpecReplicated.cpp
	gpopt/base/CDistributionSpecRouted.cpp
	gpopt/base/CDistributionSpecSingleton.cpp
	gpopt/base/CDistributionSpecStrictHashed.cpp
	gpopt/base/CDistributionSpecStrictRandom.cpp
	gpopt/base/CDistributionSpecStrictSingleton.cpp
	gpopt/base/CDistributionSpecUniversal.cpp
	gpopt/base/CDrvdProp.cpp
	gpopt/base/CDrvdPropCtxt.cpp
	gpopt/base/CDrvdPropCtxtPlan.cpp
	gpopt/base/CDrvdPropPlan.cpp
	gpopt/base/CDrvdPropRelational.cpp
	gpopt/base/CDrvdPropScalar.cpp
	gpopt/base/CEnfdDistribution.cpp
	gpopt/base/CEnfdOrder.cpp
	gpopt/base/CEnfdPartitionPropagation.cpp
	gpopt/base/CEnfdProp.cpp
	gpopt/base/CEnfdRewindability.cpp
	gpopt/base/CFunctionalDependency.cpp
	gpopt/base/CFunctionProp.cpp
	gpopt/base/CIOUtils.cpp
	gpopt/base/CKeyCollection.cpp
	gpopt/base/COptCtxt.cpp
	gpopt/base/COptimizationContext.cpp
	gpopt/base/COrderSpec.cpp
	gpopt/base/CPartFilterMap.cpp
	gpopt/base/CPartIndexMap.cpp
	gpopt/base/CPartInfo.cpp
	gpopt/base/CPartitionPropagationSpec.cpp
	gpopt/base/CPartKeys.cpp
	gpopt/base/CPrintPrefix.cpp
	gpopt/base/CPropConstraint.cpp
	gpopt/base/CQueryContext.cpp
	gpopt/base/CRange.cpp
	gpopt/base/CReqdProp.cpp
	gpopt/base/CReqdPropPlan.cpp
	gpopt/base/CReqdPropRelational.cpp
	gpopt/base/CRewindabilitySpec.cpp
	gpopt/base/CUtils.cpp
	gpopt/base/CWindowFrame.cpp
	gpopt/base/CWindowOids.cpp
	gpopt/base/IColConstraintsMapper.cpp
	gpopt/CommonException.cpp
	gpopt/cost/CCostModelGPDB.cpp
	gpopt/cost/CCostModelGPDBLegacy.cpp
	gpopt/cost/CCostModelParamsGPDB.cpp
	gpopt/cost/CCostModelParamsGPDBLegacy.cpp
	gpopt/cost/ICostModel.cpp
	gpopt/engine/CEngine.cpp
	gpopt/engine/CEnumeratorConfig.cpp
	gpopt/engine/CPartialPlan.cpp
	gpopt/engine/CStatisticsConfig.cpp
	gpopt/eval/CConstExprEvaluatorDefault.cpp
	gpopt/exception.cpp
	gpopt/init.cpp
	gpopt/metadata/CColumnDescriptor.cpp
	gpopt/metadata/CIndexDescriptor.cpp
	gpopt/metadata/CName.cpp
	gpopt/metadata/CPartConstraint.cpp
	gpopt/metadata/CTableDescriptor.cpp
	gpopt/mdcache/CMDAccessor.cpp
	gpopt/mdcache/CMDAccessorUtils.cpp
	gpopt/operators/CExpression.cpp
	gpopt/operators/CExpressionHandle.cpp
	gpopt/operators/CExpressionPreprocessor.cpp
	gpopt/operators/CLogical.cpp
	gpopt/operators/COperator.cpp
	gpopt/operators/CPattern.cpp
	gpopt/operators/CPredicateUtils.cpp
	gpopt/operators/CPhysicalAgg.cpp
	gpopt/operators/CPhysicalMotionBroadcast.cpp
	gpopt/operators/CPhysicalMotionHashDistribute.cpp
	gpopt/operators/CPhysicalMotionRandom.cpp
	gpopt/operators/CPhysicalScan.cpp
	gpopt/operators/CScalar.cpp
	gpopt/operators/CScalarArrayCmp.cpp
	gpopt/operators/CScalarArrayCoerceExpr.cpp
	gpopt/operators/CScalarCast.cpp
	gpopt/operators/CScalarCmp.cpp
	gpopt/operators/CScalarConst.cpp
	gpopt/operators/CPhysical.cpp
	gpopt/operators/CPhysicalDynamicScan.cpp
	gpopt/operators/CPhysicalMotionGather.cpp
	gpopt/operators/CPhysicalMotionRoutedDistribute.cpp
	gpopt/operators/CPhysicalUnionAll.cpp
	gpopt/base/CDatumSortedSet.cpp
	gpopt/operators/CScalarIsDistinctFrom.cpp
	gporca_dxl_stubs.cpp
	gpopt/operators/CPhysicalSort.cpp
	gpopt/operators/CPhysicalSpool.cpp
	gpopt/operators/CPhysicalPartitionSelector.cpp
	gpopt/operators/CLogicalUnary.cpp
	gpopt/operators/CScalarOp.cpp
	gpopt/operators/CScalarFunc.cpp
	gpopt/operators/CPhysicalJoin.cpp
	gpopt/operators/CScalarValuesList.cpp
	gpopt/operators/CLogicalConstTableGet.cpp
	gpopt/operators/CLogicalLimit.cpp
	gpopt/operators/CLogicalSelect.cpp
	gpopt/operators/CLogicalProject.cpp
	gpopt/operators/CLogicalGbAgg.cpp
	gpopt/operators/CLogicalSequenceProject.cpp
	gpopt/optimizer/COptimizer.cpp
	gpopt/optimizer/COptimizerConfig.cpp
	gpopt/search/CBinding.cpp
	gpopt/search/CGroup.cpp
	gpopt/search/CGroupExpression.cpp
	gpopt/search/CGroupProxy.cpp
	gpopt/search/CJob.cpp
	gpopt/search/CJobFactory.cpp
	gpopt/search/CJobGroup.cpp
	gpopt/search/CJobGroupExploration.cpp
	gpopt/search/CJobGroupExpression.cpp
	gpopt/search/CJobGroupExpressionExploration.cpp
	gpopt/search/CJobGroupExpressionImplementation.cpp
	gpopt/search/CJobGroupExpressionOptimization.cpp
	gpopt/search/CJobGroupImplementation.cpp
	gpopt/search/CJobGroupOptimization.cpp
	gpopt/search/CJobQueue.cpp
	gpopt/search/CJobTransformation.cpp
	gpopt/search/CMemo.cpp
	gpopt/search/CScheduler.cpp
	gpopt/search/CSchedulerContext.cpp
	gpopt/search/CSearchStage.cpp
	duckdb_translator/CLogicalGetDuckDB.cpp
	naucrates/init.cpp
	naucrates/base/IDatum.cpp
	naucrates/md/CMDColumn.cpp
	naucrates/md/CMDName.cpp
	naucrates/md/CSystemId.cpp
	naucrates/md/CMDProviderGeneric.cpp
	naucrates/md/IMDType.cpp
	naucrates/md/CMDIdGPDB.cpp
	naucrates/md/CMDIdGPDB.cpp
	naucrates/statistics/CBucket.cpp
	naucrates/statistics/CFilterStatsProcessor.cpp
	naucrates/statistics/CGroupByStatsProcessor.cpp
	naucrates/statistics/CHistogram.cpp
	naucrates/statistics/CInnerJoinStatsProcessor.cpp
	naucrates/statistics/CJoinStatsProcessor.cpp
	naucrates/statistics/CLeftAntiSemiJoinStatsProcessor.cpp
	naucrates/statistics/CLeftOuterJoinStatsProcessor.cpp
	naucrates/statistics/CLeftSemiJoinStatsProcessor.cpp
	naucrates/statistics/CLimitStatsProcessor.cpp
	naucrates/statistics/CPoint.cpp
	naucrates/statistics/CProjectStatsProcessor.cpp
	naucrates/statistics/CScaleFactorUtils.cpp
	naucrates/statistics/CStatistics.cpp
	naucrates/statistics/CStatisticsUtils.cpp
	naucrates/statistics/CStatsPredArrayCmp.cpp
	naucrates/statistics/CStatsPredConj.cpp
	naucrates/statistics/CStatsPredDisj.cpp
	naucrates/statistics/CStatsPredLike.cpp
	naucrates/statistics/CStatsPredPoint.cpp
	naucrates/statistics/CStatsPredUnsupported.cpp
	naucrates/statistics/CStatsPredUtils.cpp
	naucrates/statistics/CUnionAllStatsProcessor.cpp
	naucrates/statistics/CUpperBoundNDVs.cpp
	gpopt/xforms/CXformFactory.cpp
	gpos/_api.cpp
	gpos/common/CAutoTimer.cpp
	gpos/common/CBitSet.cpp
	gpos/common/CBitSetIter.cpp
	gpos/common/CBitVector.cpp
	gpos/common/CDebugCounter.cpp
	gpos/common/CHeapObject.cpp
	gpos/common/clibwrapper.cpp
	gpos/common/CMainArgs.cpp
	gpos/common/CRandom.cpp
	gpos/common/CRefCount.cpp
	gpos/common/CStackDescriptor.cpp
	gpos/common/CStackObject.cpp
	gpos/common/CTimerUser.cpp
	gpos/common/CWallClock.cpp
	gpos/common/syslibwrapper.cpp
	gpos/dlfcn.c
	gpos/error/CAutoExceptionStack.cpp
	gpos/error/CAutoTrace.cpp
	gpos/error/CErrorContext.cpp
	gpos/error/CErrorHandlerStandard.cpp
	gpos/error/CException.cpp
	gpos/error/CFSimulator.cpp
	gpos/error/CLogger.cpp
	gpos/error/CLoggerStream.cpp
	gpos/error/CLoggerSyslog.cpp
	gpos/error/CMessage.cpp
	gpos/error/CMessageRepository.cpp
	gpos/error/CMessageTable.cpp
	gpos/error/CMiniDumper.cpp
	gpos/error/CSerializable.cpp
	gpos/error/ILogger.cpp
	gpos/io/CFileDescriptor.cpp
	gpos/io/CFileReader.cpp
	gpos/io/CFileWriter.cpp
	gpos/io/COstream.cpp
	gpos/io/COstreamBasic.cpp
	gpos/io/COstreamFile.cpp
	gpos/io/COstreamStdString.cpp
	gpos/io/COstreamString.cpp
	gpos/io/ioutils.cpp
	gpos/memory/CAutoMemoryPool.cpp
	gpos/memory/CCacheFactory.cpp
	gpos/memory/CMemoryPool.cpp
	gpos/memory/CMemoryPoolManager.cpp
	gpos/memory/CMemoryPoolTracker.cpp
	gpos/memory/CMemoryVisitorPrint.cpp
	gpos/string/CStringStatic.cpp
	gpos/string/CWString.cpp
	gpos/string/CWStringBase.cpp
	gpos/string/CWStringConst.cpp
	gpos/string/CWStringDynamic.cpp
	gpos/string/CWStringStatic.cpp
	gpos/task/CAutoSuspendAbort.cpp
	gpos/task/CAutoTaskProxy.cpp
	gpos/task/CAutoTraceFlag.cpp
	gpos/task/CTask.cpp
	gpos/task/CTaskContext.cpp
	gpos/task/CTaskLocalStorage.cpp
	gpos/task/CTaskSchedulerFifo.cpp
	gpos/task/CWorker.cpp
	gpos/task/CWorkerPoolManager.cpp
	gpos/task/ITask.cpp
	gpos/task/IWorker.cpp
	gpos/utils.cpp
)

if(COMMAND add_library_unity)
	target_include_directories(duckdb_gporca PRIVATE /src/include /src/include/duckdb/gporca)
endif()

set(ALL_OBJECT_FILES
         $<TARGET_OBJECTS:duckdb_gporca>
        PARENT_SCOPE)

add_library(duckdb_gporca_stubs OBJECT gporca_stubs.cpp)
target_include_directories(duckdb_gporca_stubs PRIVATE /src/include /src/include/duckdb/gporca)
set(ALL_OBJECT_FILES  $<TARGET_OBJECTS:duckdb_gporca_stubs> PARENT_SCOPE)

add_executable(gporca_test gporca_verify.cpp)
target_include_directories(gporca_test PRIVATE /src/include /src/include/duckdb/gporca)
target_link_libraries(gporca_test PRIVATE duckdb_gporca)

